import type { Language } from "./cards";

const tr = {
  "app.tagline":"Canlı parti oyunu", "app.title":"Ekibi topla, oyunu başlat.", "app.subtitle":"Bir oyun kimliği seç, yeni bir oda aç veya altı haneli kodla katıl.",
  "profile.name":"Takma adın", "profile.random":"Rastgele ad", "profile.avatar":"Avatar seç", "profile.language":"Dil / Language",
  "room.create":"Yeni oda oluştur", "room.createHint":"Arkadaşlarını davet et ve oyunu başlat", "room.haveCode":"Oda kodun var mı?", "room.join":"Odaya katıl", "room.code":"Oda kodu", "room.copy":"Bağlantıyı kopyala", "room.copied":"Kopyalandı", "room.live":"Canlı bağlantı", "room.invite":"Davet et", "room.notFound":"Bu oda bulunamadı. Kodu kontrol et.", "room.createError":"Oda oluşturulamadı. Tekrar dene.", "room.codeError":"Altı haneli oda kodunu gir.", "room.nameError":"Önce takma adını yaz.",
  "lobby.ready":"Oda hazır", "lobby.title":"Arkadaşlarını çağır.", "lobby.subtitle":"Herkes katıldığında oyunu başlat.", "lobby.players":"Oyuncular", "lobby.summary":"Oyun özeti", "lobby.start":"Oyunu başlat", "lobby.waitHost":"Oda yöneticisi oyunu başlatacak", "lobby.needPlayers":"En az iki aktif oyuncu gerekli", "lobby.activeReady":"{count} oyuncu hazır",
  "category.condition":"Koşul", "category.vote":"Oylama", "category.duel":"IRL Düello", "category.digital":"Dijital Oyun", "category.count":"{count} kart", "category.weight":"Oran: %{value}", "category.total":"Toplam %{value}", "category.keepOne":"En az bir kategori açık kalmalı.", "category.totalError":"Aktif kategori oranlarının toplamı %100 olmalı.",
  "content.light":"Hafif", "content.normal":"Normal", "content.hard":"Sert",
  "game.round":"Tur {current} / {total}", "game.roundInfinite":"Tur {current} / ∞", "game.turnYou":"Sıra sende", "game.turnPlayer":"Sıra {name} adlı oyuncuda", "game.open":"Kartı aç", "game.waitOpen":"{name} kartını açacak", "game.pass":"Pas", "game.passLeft":"{count} hak", "game.next":"Sonraki tur", "game.finish":"Oyunu bitir", "game.confirm":"Sonucu kaydet", "game.responses":"{done}/{total} cevap", "game.answer":"Bu tur içtin mi?", "game.drank":"İçtim", "game.notDrank":"İçmedim", "game.waitAnswers":"Diğer cevaplar bekleniyor", "game.everyoneAnswered":"Herkes cevapladı", "game.paused":"Oyuna mola verildi", "game.resume":"Oyuna devam et", "game.finished":"Oyun tamamlandı", "game.home":"Ana ekrana dön", "game.noCard":"Uygun kart bulunamadı.",
  "vote.title":"Gizli oylama", "vote.choose":"{count} kişi seç", "vote.send":"Oyunu gönder", "vote.saved":"Oyun kaydedildi", "vote.wait":"Oylar bekleniyor", "vote.result":"Oylama sonucu", "vote.votes":"{count} oy", "vote.revote":"Eşitlik oldu, yeniden oyla", "vote.openBallot":"Oylar canlı görünür", "vote.secretBallot":"Oylar sonuç açıklanana kadar gizlidir",
  "mini.readyTitle":"Hazır olduğunda katıl", "mini.ready":"Hazırım", "mini.readyDone":"Hazırsın", "mini.readyCount":"{done}/{total} hazır", "mini.countdown":"Aynı anda başlıyor", "mini.watch":"Canlı izliyorsun", "mini.watchHint":"Oyuncuların durumu bütün cihazlarda aynı anda güncellenir.", "mini.locked":"Cevabın kilitlendi", "mini.waitPlayers":"Diğer oyuncular bekleniyor", "mini.result":"Doğrulanmış sonuç", "mini.restart":"Yeniden başlat", "mini.cancel":"Mini oyunu iptal et", "mini.confirm":"Sonucu onayla", "mini.chooseOpponent":"Rakip seç", "mini.opponentWaiting":"{name} rakibini seçiyor", "mini.yourMove":"Hamle sırası sende", "mini.theirMove":"{name} hamle yapıyor", "mini.draw":"Berabere", "mini.winner":"{name} kazandı", "mini.losers":"Kaybedenler", "mini.noLoser":"Bu oyunda kimse kaybetmedi", "mini.excluded":"Bu turu seyirci olarak izliyorsun", "mini.remove":"Bu turdan çıkar",
  "mini.odd_one":"Farklı olan sembole dokun", "mini.reflexWait":"Yeşili bekle", "mini.reflexGo":"Şimdi dokun", "mini.rapid":"Beş saniye boyunca dokun", "mini.five":"Tam beş saniyede durdur", "mini.emojiShow":"Sırayı ezberle", "mini.emojiPick":"Sembolleri sırayla seç", "mini.trust":"Güven", "mini.betray":"İhanet", "mini.secret":"Seçimin sonuç açıklanana kadar gizli", "mini.math":"İşlemi çöz", "mini.xox":"Boş bir hücre seç", "mini.bombHolder":"Bomba {name} adlı oyuncuda", "mini.bombYou":"Bomba sende", "mini.bombPass":"Bombayı gönder", "mini.bombLocked":"Gönderme süren doldu", "mini.common":"Gizli cevabını seç", "mini.choiceMade":"Seçimini yaptı", "mini.early":"Hatalı başlangıç", "mini.timeout":"Süre doldu", "mini.ms":"{value} ms", "mini.seconds":"{value} sn", "mini.taps":"{value} dokunuş",
  "result.taking":"Shot atanlar", "result.single":"{name} shot atıyor", "result.safe":"Bu tur kimse içmiyor", "result.everyoneSafe":"Herkes kurtuldu", "result.more":"+{count} oyuncu", "result.skip":"Geç", "result.continue":"Devam et", "result.choice":"{name}: {choice}",
  "players.title":"Oyuncular", "players.host":"Yönetici", "players.you":"Sen", "players.online":"Çevrimiçi", "players.reconnecting":"Yeniden bağlanıyor", "players.spectator":"İzleyici", "players.turn":"{number}. sırada", "players.shot":"shot", "players.manage":"Yönet", "players.moveUp":"Yukarı taşı", "players.moveDown":"Aşağı taşı",
  "settings.title":"Ayarlar", "settings.future":"Gelecek Turlar", "settings.categories":"Kart Kategorileri", "settings.length":"Oyun Uzunluğu", "settings.content":"İçerik Seviyesi", "settings.digital":"Dijital Oyunlar", "settings.duels":"IRL Düellolar", "settings.voting":"Oylama Ayarları", "settings.management":"Oyun Yönetimi", "settings.audio":"Ses ve Titreşim", "settings.leave":"Oyundan Çık", "settings.sound":"Ses efektleri", "settings.vibration":"Titreşim", "settings.reduceMotion":"Animasyonu azalt", "settings.on":"Açık", "settings.off":"Kapalı", "settings.applyNext":"Değişiklikler sonraki karttan itibaren uygulanır.", "settings.rounds":"Toplam tur", "settings.infinite":"Sınırsız oyun", "settings.endAt":"Bu tur sonunda bitir", "settings.passes":"Kişi başı pas", "settings.weights":"Kategori oranları", "settings.digitalAll":"Dijital oyunlar", "settings.twoPlayer":"İki kişilik oyunlar", "settings.groupGames":"Grup oyunları", "settings.noRepeat":"Aynı mini oyunu tekrarlama", "settings.duelOpponent":"Rakip seçimi", "settings.openerChooses":"Kartı açan seçsin", "settings.systemChooses":"Sistem seçsin", "settings.noConsecutiveOpponent":"Aynı rakip art arda gelmesin", "settings.phoneCards":"Telefon içeriği isteyen kartlar", "settings.trivia":"Bilgi oyunları", "settings.groupVoteDuels":"Grup oylamalı düellolar", "settings.votePrivacy":"Oy gizliliği", "settings.secret":"Gizli", "settings.open":"Açık", "settings.distribution":"Oy dağılımını göster", "settings.allResults":"Tüm sonuçları göster", "settings.winnerOnly":"Yalnızca kazanan", "settings.selfVote":"Kendine oy verme", "settings.tie":"Eşitlik", "settings.tieDrink":"Tüm eşitler içsin", "settings.tieRevote":"Yeniden oylama", "settings.hostConfirm":"Host onayı zorunlu", "settings.autoSave":"Otomatik sonuç kaydı", "settings.autoAdvance":"Otomatik sonraki tur", "settings.pause":"Oyunu duraklat", "settings.undo":"Son sonucu geri al", "settings.replay":"Son kartı yeniden oyna", "settings.redraw":"Gelecek kartı yeniden seç", "settings.skipTurn":"Sırayı atla", "settings.shots":"Shot sayılarını düzenle", "settings.transfer":"Hostluğu devret", "settings.spectate":"İzleyici yap", "settings.activate":"Oyuncu yap", "settings.kick":"Odadan çıkar", "settings.end":"Oyunu erken bitir", "settings.confirmTitle":"Emin misin?", "settings.confirmText":"Bu işlem odadaki bütün oyuncuları etkileyebilir.", "settings.cancel":"Vazgeç", "settings.accept":"Onayla",
  "language.tr":"Türkçe", "language.en":"English", "common.close":"Kapat", "common.back":"Geri", "common.save":"Kaydet", "common.status":"Durum", "common.loading":"Hazırlanıyor", "common.none":"Yok", "common.live":"Canlı", "common.error":"Bir sorun oluştu. Tekrar dene.", "common.responsible":"18+ · Sorumlu tüket. Alkolsüz de oynanır.",
  "miniName.odd_one":"Farklı Olanı Bul", "miniName.reflex":"Refleks", "miniName.rapid_tap":"Hızlı Dokunma", "miniName.five_seconds":"Beş Saniyeyi Yakala", "miniName.emoji_memory":"Emoji Sıralaması", "miniName.trust":"Güven mi, İhanet mi?", "miniName.quick_math":"Hızlı Hesap", "miniName.xox":"XOX", "miniName.bomb":"Bomba Kimde?", "miniName.common_answer":"Ortak Cevap",
} as const;

const en: Record<keyof typeof tr, string> = {
  "app.tagline":"Live party game", "app.title":"Gather the crew. Start the game.", "app.subtitle":"Choose a game identity, create a room, or join with a six-digit code.",
  "profile.name":"Nickname", "profile.random":"Random name", "profile.avatar":"Choose avatar", "profile.language":"Dil / Language",
  "room.create":"Create new room", "room.createHint":"Invite your friends and start the game", "room.haveCode":"Have a room code?", "room.join":"Join room", "room.code":"Room code", "room.copy":"Copy invite link", "room.copied":"Copied", "room.live":"Live connection", "room.invite":"Invite", "room.notFound":"Room not found. Check the code.", "room.createError":"The room could not be created. Try again.", "room.codeError":"Enter the six-digit room code.", "room.nameError":"Enter a nickname first.",
  "lobby.ready":"Room ready", "lobby.title":"Invite your friends.", "lobby.subtitle":"Start when everyone has joined.", "lobby.players":"Players", "lobby.summary":"Game summary", "lobby.start":"Start game", "lobby.waitHost":"The host will start the game", "lobby.needPlayers":"At least two active players are required", "lobby.activeReady":"{count} players ready",
  "category.condition":"Condition", "category.vote":"Voting", "category.duel":"IRL Duel", "category.digital":"Digital Game", "category.count":"{count} cards", "category.weight":"Weight: {value}%", "category.total":"Total {value}%", "category.keepOne":"At least one category must stay active.", "category.totalError":"Active category weights must add up to 100%.",
  "content.light":"Light", "content.normal":"Normal", "content.hard":"Hard",
  "game.round":"Round {current} / {total}", "game.roundInfinite":"Round {current} / ∞", "game.turnYou":"Your turn", "game.turnPlayer":"{name}'s turn", "game.open":"Open card", "game.waitOpen":"{name} will open the card", "game.pass":"Pass", "game.passLeft":"{count} left", "game.next":"Next round", "game.finish":"Finish game", "game.confirm":"Save result", "game.responses":"{done}/{total} answered", "game.answer":"Did you take a shot this round?", "game.drank":"I did", "game.notDrank":"I didn't", "game.waitAnswers":"Waiting for other answers", "game.everyoneAnswered":"Everyone answered", "game.paused":"Game paused", "game.resume":"Resume game", "game.finished":"Game complete", "game.home":"Back to home", "game.noCard":"No eligible card is available.",
  "vote.title":"Secret vote", "vote.choose":"Choose {count}", "vote.send":"Submit vote", "vote.saved":"Vote saved", "vote.wait":"Waiting for votes", "vote.result":"Voting result", "vote.votes":"{count} votes", "vote.revote":"Tie — vote again", "vote.openBallot":"Votes are visible live", "vote.secretBallot":"Votes stay hidden until results are revealed",
  "mini.readyTitle":"Join when ready", "mini.ready":"I'm ready", "mini.readyDone":"Ready", "mini.readyCount":"{done}/{total} ready", "mini.countdown":"Starting together", "mini.watch":"Watching live", "mini.watchHint":"The game state updates on every device at the same time.", "mini.locked":"Your answer is locked", "mini.waitPlayers":"Waiting for other players", "mini.result":"Verified result", "mini.restart":"Restart", "mini.cancel":"Cancel mini-game", "mini.confirm":"Confirm result", "mini.chooseOpponent":"Choose opponent", "mini.opponentWaiting":"{name} is choosing an opponent", "mini.yourMove":"Your move", "mini.theirMove":"{name} is playing", "mini.draw":"Draw", "mini.winner":"{name} won", "mini.losers":"Losers", "mini.noLoser":"Nobody lost this game", "mini.excluded":"You are watching this round", "mini.remove":"Remove from this round",
  "mini.odd_one":"Tap the different symbol", "mini.reflexWait":"Wait for green", "mini.reflexGo":"Tap now", "mini.rapid":"Tap for five seconds", "mini.five":"Stop at exactly five seconds", "mini.emojiShow":"Memorize the order", "mini.emojiPick":"Select the symbols in order", "mini.trust":"Trust", "mini.betray":"Betray", "mini.secret":"Your choice stays hidden until the result", "mini.math":"Solve the calculation", "mini.xox":"Choose an empty square", "mini.bombHolder":"{name} has the bomb", "mini.bombYou":"You have the bomb", "mini.bombPass":"Pass the bomb", "mini.bombLocked":"Your pass time is over", "mini.common":"Choose your secret answer", "mini.choiceMade":"Choice locked", "mini.early":"False start", "mini.timeout":"Time expired", "mini.ms":"{value} ms", "mini.seconds":"{value} sec", "mini.taps":"{value} taps",
  "result.taking":"Taking a shot", "result.single":"{name} takes a shot", "result.safe":"No shots this round", "result.everyoneSafe":"Everyone is safe", "result.more":"+{count} players", "result.skip":"Skip", "result.continue":"Continue", "result.choice":"{name}: {choice}",
  "players.title":"Players", "players.host":"Host", "players.you":"You", "players.online":"Online", "players.reconnecting":"Reconnecting", "players.spectator":"Spectator", "players.turn":"Position {number}", "players.shot":"shot", "players.manage":"Manage", "players.moveUp":"Move up", "players.moveDown":"Move down",
  "settings.title":"Settings", "settings.future":"Future Rounds", "settings.categories":"Card Categories", "settings.length":"Game Length", "settings.content":"Content Level", "settings.digital":"Digital Games", "settings.duels":"IRL Duels", "settings.voting":"Voting Settings", "settings.management":"Game Management", "settings.audio":"Sound & Vibration", "settings.leave":"Leave Game", "settings.sound":"Sound effects", "settings.vibration":"Vibration", "settings.reduceMotion":"Reduce motion", "settings.on":"On", "settings.off":"Off", "settings.applyNext":"Changes apply from the next card.", "settings.rounds":"Total rounds", "settings.infinite":"Unlimited game", "settings.endAt":"End after this round", "settings.passes":"Passes per player", "settings.weights":"Category weights", "settings.digitalAll":"Digital games", "settings.twoPlayer":"Two-player games", "settings.groupGames":"Group games", "settings.noRepeat":"Prevent repeated mini-games", "settings.duelOpponent":"Opponent selection", "settings.openerChooses":"Card opener chooses", "settings.systemChooses":"System chooses", "settings.noConsecutiveOpponent":"Do not repeat the same opponent", "settings.phoneCards":"Cards requiring phone content", "settings.trivia":"Trivia games", "settings.groupVoteDuels":"Group-vote duels", "settings.votePrivacy":"Vote privacy", "settings.secret":"Secret", "settings.open":"Open", "settings.distribution":"Show vote distribution", "settings.allResults":"Show all results", "settings.winnerOnly":"Winner only", "settings.selfVote":"Allow self-voting", "settings.tie":"Tie handling", "settings.tieDrink":"All tied players drink", "settings.tieRevote":"Vote again", "settings.hostConfirm":"Require host confirmation", "settings.autoSave":"Auto-save results", "settings.autoAdvance":"Auto-advance", "settings.pause":"Pause game", "settings.undo":"Undo last result", "settings.replay":"Replay current card", "settings.redraw":"Redraw next card", "settings.skipTurn":"Skip turn", "settings.shots":"Edit shot totals", "settings.transfer":"Transfer host", "settings.spectate":"Make spectator", "settings.activate":"Make player", "settings.kick":"Remove from room", "settings.end":"End game early", "settings.confirmTitle":"Are you sure?", "settings.confirmText":"This action may affect everyone in the room.", "settings.cancel":"Cancel", "settings.accept":"Confirm",
  "language.tr":"Türkçe", "language.en":"English", "common.close":"Close", "common.back":"Back", "common.save":"Save", "common.status":"Status", "common.loading":"Preparing", "common.none":"None", "common.live":"Live", "common.error":"Something went wrong. Try again.", "common.responsible":"18+ · Drink responsibly. Plays great alcohol-free too.",
  "miniName.odd_one":"Find the Odd One", "miniName.reflex":"Reflex", "miniName.rapid_tap":"Rapid Tap", "miniName.five_seconds":"Catch Five Seconds", "miniName.emoji_memory":"Emoji Sequence", "miniName.trust":"Trust or Betray?", "miniName.quick_math":"Quick Math", "miniName.xox":"Tic-tac-toe", "miniName.bomb":"Who Has the Bomb?", "miniName.common_answer":"Common Answer",
};

export type TranslationKey = keyof typeof tr;
export const translations = { tr, en };
export function translate(language: Language, key: TranslationKey, values: Record<string,string|number> = {}) {
  let text: string = translations[language][key] ?? tr[key];
  for (const [name, value] of Object.entries(values)) text = text.replaceAll(`{${name}}`, String(value));
  return text;
}

export const randomNameParts = {
  tr: [["Neşeli","Cesur","Parlak","Meraklı","Hızlı","Sakin","Şanslı","Gizemli"],["Panda","Tilki","Koala","Penguen","Kaplan","Kurbağa","Aslan","Baykuş"]],
  en: [["Happy","Brave","Bright","Curious","Swift","Calm","Lucky","Mysterious"],["Panda","Fox","Koala","Penguin","Tiger","Frog","Lion","Owl"]],
} as const;

export const commonGameText = {
  tr: { color:"Bir renk seç",animal:"Bir hayvan seç",drink:"Bir içecek seç",season:"Bir mevsim seç",country:"Bir ülke seç",red:"Kırmızı",blue:"Mavi",green:"Yeşil",yellow:"Sarı",purple:"Mor",black:"Siyah",cat:"Kedi",dog:"Köpek",fox:"Tilki",lion:"Aslan",panda:"Panda",owl:"Baykuş",water:"Su",coffee:"Kahve",tea:"Çay",soda:"Gazoz",juice:"Meyve suyu",spring:"İlkbahar",summer:"Yaz",autumn:"Sonbahar",winter:"Kış",turkey:"Türkiye",italy:"İtalya",japan:"Japonya",spain:"İspanya",brazil:"Brezilya",france:"Fransa" },
  en: { color:"Choose a color",animal:"Choose an animal",drink:"Choose a drink",season:"Choose a season",country:"Choose a country",red:"Red",blue:"Blue",green:"Green",yellow:"Yellow",purple:"Purple",black:"Black",cat:"Cat",dog:"Dog",fox:"Fox",lion:"Lion",panda:"Panda",owl:"Owl",water:"Water",coffee:"Coffee",tea:"Tea",soda:"Soda",juice:"Juice",spring:"Spring",summer:"Summer",autumn:"Autumn",winter:"Winter",turkey:"Türkiye",italy:"Italy",japan:"Japan",spain:"Spain",brazil:"Brazil",france:"France" },
} as const;
